api.error do
  api.error "cannot call each on api"
end